branch-defaults:
  default:
    environment: udagram-api-dev
    group_suffix: null
deploy:
  artifact: www/Archive.zip
  accessKeyId : process.env.AWS_ACCESS_KEY_ID
secretAccessKey : process.env.AWS_SECRET_ACCESS_KEY
global:
  application_name: udagram-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
  accessKeyId : process.env.AWS_ACCESS_KEY_ID
  secretAccessKey : process.env.AWS_SECRET_ACCESS_KEY
